routes/web.php
<?php

/**
 * Global Routes
 * Routes that are used between both frontend and backend.
 */

// Switch between the included languages
Route::get('lang/{lang}', 'LanguageController');

/*
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    include_route_files(__DIR__.'/frontend/');
});

/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    /*
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     * These routes can not be hit if the password is expired
     */
    include_route_files(__DIR__.'/backend/');
});

Route::group(['namespace' => 'Backend', 'prefix' => 'admin'], function() {
    Route::get('/login',
        'Auth\AdminLoginController@showLoginForm')->name('backend.admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('backend.admin.login.submit');
    Route::get('logout/', 'Auth\AdminLoginController@logout')->name('backend.admin.logout');
});

app/Models/Survey.php
<?php

namespace App\Models;

use App\Models\Auth\User;
use Illuminate\Database\Eloquent\Model;

class Survey extends Model
{
    protected $fillable = [
        'name',
        'description',
        'active',
    ];

    public function surveyQuestions()
    {
        return $this->hasMany(SurveyQuestion::class);
    }

    public function users()
    {
        return $this->belongsToMany(Auth\User::class);
    }

    /**
     * @return string
     */
    public function getShowButtonAttribute()
    {
        return '<a href="'.route('admin.surveys.show', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.view').'" class="btn btn-info"><i class="fas fa-eye text-white"></i></a>';
    }

    /**
     * @return string
     */
    public function getEditButtonAttribute()
    {
        return '<a href="'.route('admin.surveys.edit', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.edit').'" class="btn btn-primary"><i class="fas fa-edit text-white"></i></a>';
    }

    /**
     * @return string
     */
    public function getDeleteButtonAttribute()
    {
        return '<a href="'.route('admin.surveys.destroy', $this).'"
			 data-method="delete"
			 data-trans-button-cancel="'.__('buttons.general.cancel').'"
			 data-trans-button-confirm="'.__('buttons.general.crud.delete').'"
			 data-trans-title="'.__('strings.backend.general.are_you_sure').'"
			 class="btn btn-danger"><i class="fas fa-trash text-white" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.delete').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
        return '
    	<div class="btn-group" role="group" aria-label="Survey Actions">
		  '.$this->show_button.'
		  '.$this->edit_button.'
		  '.$this->delete_button.'
		</div>';
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

/**
 * Class DashboardController.
 */
class DashboardController extends Controller
{
    /**
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('backend.dashboard');
    }
}

app/Http/Controllers/Backend/ModulesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Module;
use App\Models\ModuleQuestion;
use App\Repositories\Backend\ModuleRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ModulesController extends Controller
{
    protected $moduleRepository;

    public function __construct(ModuleRepository $moduleRepository)
    {
        $this->moduleRepository = $moduleRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.modules.index')
            ->withModules($this->moduleRepository->getActivePaginated(25, 'id', 'asc'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.modules.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $updateData = $request->only(['name', 'description', 'instructor', 'video_url']);
        $questions = $request->input('questions', []);
        $preQuestions = collect(array_get($questions,'pre', []))->pluck('question_data');
        $postQuestions = collect(array_get($questions,'post', []))->pluck('question_data');
        $module = Module::create($updateData);

        if (count($preQuestions) > 0) {
            foreach($preQuestions as $index => $question) {
                if (strlen(trim($question['question_text']))) {
                    $question['id'] = isset($question['id']) ? $question['id'] : null;
                    $question['pre_or_post'] = 'pre';
                    $question['module_id'] = $module->id;
                    $question['question_number'] = $index + 1;
                    $questionRecord = ModuleQuestion::updateOrCreate(['id' => $question['id']], $question);
                }
            }
        }

        if (count($postQuestions) > 0) {
            foreach($postQuestions as $index => $question) {
                if (strlen(trim($question['question_text']))) {
                    $question['id'] = isset($question['id']) ? $question['id'] : null;
                    $question['pre_or_post'] = 'post';
                    $question['module_id'] = $module->id;
                    $question['question_number'] = $index + 1;
                    $questionRecord = ModuleQuestion::updateOrCreate(['id' => $question['id']], $question);
                }
            }
        }

        $request->session()->flash('flash_success', __('alerts.backend.modules.created'));

        return $module;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('backend.modules.show')
            ->withModule(Module::with(['questions', 'students'])->find($id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Module  $module
     * @return \Illuminate\Http\Response
     */
    public function edit(Module $module)
    {
        $modulePreQuestions = $module->questions()
            ->where('pre_or_post', '=', 'pre')->orderBy('question_number')->get()
            ->map(function ($question) {
                return [
                    'id' => $question->id,
                    'question_answer' => $question->question_answer,
                    'question_text' => $question->question_text,
                    'question_type' => $question->question_type,
                    'question_options' => $question->question_options,
                ];
            });

        $modulePostQuestions = $module->questions()
            ->where('pre_or_post', '=', 'post')->orderBy('question_number')->get()
            ->map(function ($question) {
                return [
                    'id' => $question->id,
                    'question_answer' => $question->question_answer,
                    'question_text' => $question->question_text,
                    'question_type' => $question->question_type,
                    'question_options' => $question->question_options,
                ];
            });
        return view('backend.modules.edit')
            ->withModule(collect([
                "id" => $module->id,
                "name" => $module->name,
                "description" => $module->description,
                "instructor" => $module->instructor,
                "video_url" => $module->video_url,
                "questions" => [
                    "pre" => $modulePreQuestions,
                    "post" => $modulePostQuestions,
                ]
            ]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Module  $module
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Module $module)
    {
        $updateData = $request->only(['name', 'description', 'instructor', 'video_url']);
        $questions = $request->input('questions', []);
        $preQuestions = collect(array_get($questions,'pre', []))->pluck('question_data');
        $postQuestions = collect(array_get($questions,'post', []))->pluck('question_data');
        $saved = $module->update($updateData);

        if (count($preQuestions) > 0) {
            foreach($preQuestions as $index => $question) {
                if (strlen(trim($question['question_text']))) {
                    $question['id'] = isset($question['id']) ? $question['id'] : null;
                    $question['pre_or_post'] = 'pre';
                    $question['module_id'] = $module->id;
                    $question['question_number'] = $index + 1;
                    $questionRecord = ModuleQuestion::updateOrCreate(['id' => $question['id']], $question);
                }
            }
        }

        if (count($postQuestions) > 0) {
            foreach($postQuestions as $index => $question) {
                if (strlen(trim($question['question_text']))) {
                    $question['id'] = isset($question['id']) ? $question['id'] : null;
                    $question['pre_or_post'] = 'post';
                    $question['module_id'] = $module->id;
                    $question['question_number'] = $index + 1;
                    $questionRecord = ModuleQuestion::updateOrCreate(['id' => $question['id']], $question);
                }
            }
        }

        $request->session()->flash('flash_success', __('alerts.backend.modules.updated'));

        return $module;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->moduleRepository->deleteById($id);

        return redirect()->route('admin.modules.index')
            ->withFlashSuccess(__('alerts.backend.modules.deleted'));
    }
}

app/Http/Controllers/Backend/OrganizationsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests\Backend\StoreOrganizationRequest;
use App\Http\Requests\Backend\UpdateOrganizationRequest;
use App\Models\Module;
use App\Models\Organization;
use App\Models\OrganizationType;
use App\Repositories\Backend\OrganizationRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrganizationsController extends Controller
{
    protected $organizationRepository;

    public function __construct(OrganizationRepository $organizationRepository)
    {
        $this->organizationRepository = $organizationRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.organizations.index')
            ->withOrganizations($this->organizationRepository->getActivePaginated(25, 'id', 'asc'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.organizations.create')
            ->withOrganizationTypes(OrganizationType::all()->map(function ($type) {
            return ['value' => $type->id, 'label' => $type->name];
        }));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreOrganizationRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreOrganizationRequest $request)
    {
        $requestData = $request->only([
            'name',
            'type_id',
            'address_1',
            'address_2',
            'city',
            'state',
            'zip',
            'phone',
        ]);
        $type = $request->input('type');

        if (!$requestData['type_id'] && $type['label']) {
            $organizationType = OrganizationType::updateOrCreate(['name' => $type['label']]);
            $requestData['type_id'] = $organizationType->id;
        }

        $organization = Organization::create($requestData);

        $request->session()->flash('flash_success', __('alerts.backend.organizations.created'));

        return $organization;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('backend.organizations.show')
            ->withOrganization(Organization::with(['users', 'students'])->find($id))
            ->withModules(Module::all());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Organization $organization)
    {
        return view('backend.organizations.edit')
            ->withOrganization($organization)
            ->withOrganizationTypes(OrganizationType::all()->map(function ($type) {
                return ['value' => $type->id, 'label' => $type->name];
            }));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateOrganizationRequest  $request
     * @param  Organization  $organization
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateOrganizationRequest $request, Organization $organization)
    {
        $requestData = $request->only([
            'name',
            'type_id',
            'address_1',
            'address_2',
            'city',
            'state',
            'zip',
            'phone',
        ]);
        $type = $request->input('type');

        if (!$requestData['type_id'] && $type['label']) {
            $organizationType = OrganizationType::updateOrCreate(['name' => $type['label']]);
            $requestData['type_id'] = $organizationType->id;
        }
        $organization->update($requestData);

        $request->session()->flash('flash_success', __('alerts.backend.organizations.updated'));

        return $organization;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->organizationRepository->deleteById($id);

        return redirect()->route('admin.organizations.index')
            ->withFlashSuccess(__('alerts.backend.organizations.deleted'));
    }

    public function organizationTypes(Request $request)
    {
        $query = $request->get('query', null);
        if ($query) {
            $organizationTypes = OrganizationType::where('name', 'LIKE', "%${query}%")->get();
        } else {
            $organizationTypes = OrganizationType::all();
        }

        $organizationTypes->transform(function ($type) {
            return ['value' => $type->id, 'label' => $type->name];
        });

        return response()->json([
            'status' => 'success',
            'data' => $organizationTypes,
        ]);
    }
}

app/Http/Controllers/Backend/QuestionsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Repositories\Backend\ModuleQuestionRepository;
use App\Http\Controllers\Controller;
use App\Repositories\Backend\SurveyQuestionRepository;

class QuestionsController extends Controller
{
    protected $moduleQuestionRepository;
    protected $surveyQuestionRepository;

    public function __construct(ModuleQuestionRepository $moduleQuestionRepository, SurveyQuestionRepository $surveyQuestionRepository)
    {
        $this->moduleQuestionRepository = $moduleQuestionRepository;
        $this->surveyQuestionRepository = $surveyQuestionRepository;
    }

    public function questionDeleteStatus($type, $id)
    {
        $repo = $type === 'module' ? $this->moduleQuestionRepository : $this->surveyQuestionRepository;
        $question =  $repo->getById($id);

        if (!$question) {
            return response()->json(['status' => 'error', 'message' => 'Couldn\'t find question'])->status(401);
        }

        $hasResponses = $question->studentResponses()->count();

        if ($hasResponses) {
            return response()->json([
                'status' => 'success',
                'data' => [
                    'hasQuestions' => true,
                ]
            ]);
        }
        return response()->json([
            'status' => 'success',
            'data' => [
                'hasQuestions' => false,
            ]
        ]);
    }

    public function deleteQuestion($type, $id)
    {
        $repo = $type === 'module' ? $this->moduleQuestionRepository : $this->surveyQuestionRepository;
        $question =  $repo->getById($id);
        if ($question) {
            $question->studentResponses()->delete();
        }

        $question->delete();
        return response()->json([
            'status' => 'success',
        ]);
    }
}

resources/views/backend/surveys/create.blade.php
@extends ('backend.layouts.app')

@section ('title', __('labels.backend.surveys.management') . ' | ' . __('labels.backend.surveys.create'))

@section('breadcrumb-links')
    @include('backend.surveys.includes.breadcrumb-links')
@endsection

@section('content')
    <survey-form></survey-form>
@endsection

resources/views/backend/surveys/edit.blade.php
@extends ('backend.layouts.app')

@section ('title', __('labels.backend.surveys.management') . ' | ' . __('labels.backend.surveys.edit'))

@section('breadcrumb-links')
    @include('backend.surveys.includes.breadcrumb-links')
@endsection

@section('content')
    <survey-form :survey-form-data="{{ $survey->toJson() }}"></survey-form>
@endsection

resources/views/backend/surveys/index.blade.php
@extends ('backend.layouts.app')

@section ('title', app_name() . ' | ' . __('labels.backend.surveys.management'))

@section('breadcrumb-links')
    @include('backend.surveys.includes.breadcrumb-links')
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('labels.backend.surveys.management') }}
                </h4>
            </div><!--col-->

            <div class="col-sm-7">
                @include('backend.surveys.includes.header-buttons')
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4">
            <div class="col">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>{{ __('labels.backend.surveys.table.name') }}</th>
                            <th>{{ __('labels.backend.surveys.table.description') }}</th>
                            <th>{{ __('labels.general.actions') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($surveys as $survey)
                            <tr>
                                <td>{{ $survey->name }}</td>
                                <td>{{ $survey->description }}</td>
                                <td>{!! $survey->action_buttons !!}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div><!--col-->
        </div><!--row-->
        <div class="row">
            <div class="col-7">
                <div class="float-left">
                    {!! $surveys->total() !!} {{ trans_choice('labels.backend.surveys.table.total', $surveys->total()) }}
                </div>
            </div><!--col-->

            <div class="col-5">
                <div class="float-right">
                    {!! $surveys->render() !!}
                </div>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->
</div><!--card-->
@endsection

resources/views/backend/surveys/show.blade.php
@extends ('backend.layouts.app')

@section ('title', __('labels.backend.organizations.management') . ' | ' . __('labels.backend.organizations.view'))

@section('breadcrumb-links')
    @include('backend.auth.user.includes.breadcrumb-links')
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        {{ __('labels.backend.surveys.management') }}
                        <small class="text-muted">{{ __('labels.backend.surveys.view') }}</small>
                    </h4>
                </div><!--col-->
                <div class="col ml-auto text-right">
                    <a href="{{route('admin.surveys.edit', $survey)}}" data-toggle="tooltip" data-placement="top" title="{{__('buttons.general.crud.edit')}}" class="btn btn-primary">Edit</a>
                </div>
            </div><!--row-->
            <div class="row mt-4">
                <div class="col">
                    <h2>{{ $survey->name }}</h2>
                </div>
            </div>
            <div class="row mb-4">
                <div class="col-8">
                    <p>{{ $survey->description }}</p>
                </div>
            </div>

            <div class="row mt-4 mb-4">
                <div class="col">
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#pre" role="tab" aria-controls="pre" aria-expanded="true">Survey Questions</a>
                        </li>
                    </ul>

                    <div class="tab-content">
                        <div class="tab-pane active" id="pre" role="tabpanel" aria-expanded="true">
                            @foreach($survey->surveyQuestions as $question )
                                <div>
                                    <div class="text-left">
                                        <strong>Question #{{ $question->question_number }}</strong>
                                    </div>
                                    <h3 class="text-left mt-2 mb-4">{{ $question->question_text}}</h3>
                                </div>
                                @switch($question->question_type)
                                    @case('multiple_choice')
                                    <div class="mb-4">
                                        <div class="margin-center">
                                            <div class="row">
                                                @foreach($question->question_options as $key => $option)
                                                    <div class="col-sm-6 col-12 col-xl-3 text-left" >
                                                        <label class="radio-label row align-items-baseline">
                                                            <div class="col-auto">
                                                                <input
                                                                        type="radio"
                                                                        class="option-input radio"
                                                                />
                                                            </div>
                                                            <div class="col">{{ $option }}</div>
                                                        </label>
                                                    </div>
                                                @endforeach
                                            </div>
                                        </div>
                                    </div>
                                    @break
                                    @case('short_answer')
                                    <div class="mb-4">
                                        <div class="form-group">
                                            <input
                                                    type="text"
                                                    placeholder="Type your Answer"
                                                    class="form-control"
                                            >
                                        </div>
                                    </div>
                                    @break
                                    @case('paragraph')
                                    <div class="mb-4">
                                        <div class="form-group">
                                      <textarea
                                              placeholder="Type your Answer"
                                              rows="5"
                                              class="form-control"
                                      ></textarea>
                                        </div>
                                    </div>
                                    @break
                                    @case('true_false')
                                    <div class="mb-4">
                                        <label class="radio-label mr-2 clickable">
                                            <input
                                                    type="radio"
                                                    class="option-input radio"
                                                    value="1"
                                            />
                                            True
                                        </label>
                                        <label class="radio-label ml-2 clickable">
                                            <input
                                                    type="radio"
                                                    class="option-input radio"
                                                    value="0"
                                            />
                                            False
                                        </label>
                                    </div>
                                    @break
                                @endswitch
                            @endforeach
                        </div><!--tab-->
                    </div><!--tab-content-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    <small class="float-right text-muted">

                    </small>
                </div><!--col-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
@endsection